services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: eventDiscovery  # Changed to match your web service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: myuser
      DB_PWD: mypassword
      DATABASE_NAME: eventDiscovery
      MYSQL2_VERSION: '0.5.5'

volumes:
  db_data: