services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myapp_production
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: myuser
      DB_PWD: mypassword
      DATABASE_NAME: eventDiscovery
      MYSQL2_VERSION: '0.5.5' # si nécessaire

volumes:
  db_data:
